data_baddies_datafest:
  target: RAW
  outputs:
    RAW:
      account: ya78182.eu-west-2.aws
      database: DATAFESTAFRICA
      password: '@Databaddies2_'
      role: ACCOUNTADMIN
      schema: RAW
      threads: 1
      type: snowflake
      user: databaddies2024
      warehouse: COMPUTE_WH
    INTERMEDIATE:
      account: ya78182.eu-west-2.aws
      database: DATAFESTAFRICA
      password: '@Databaddies2_'
      role: ACCOUNTADMIN
      schema: INTERMEDIATE
      threads: 1
      type: snowflake
      user: databaddies2024
      warehouse: COMPUTE_WH
    CORE:
      account: ya78182.eu-west-2.aws
      database: DATAFESTAFRICA
      password: '@Databaddies2_'
      role: ACCOUNTADMIN
      schema: CORE
      threads: 1
      type: snowflake
      user: databaddies2024
      warehouse: COMPUTE_WH
