data_baddies_datafest:
  target: RAW
  outputs:
    RAW:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: DATAFESTAFRICA
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: RAW
      threads: 1
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
    INTERMEDIATE:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: DATAFESTAFRICA
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: INTERMEDIATE
      threads: 1
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
    CORE:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: DATAFESTAFRICA
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: CORE
      threads: 1
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
